// Generated by Wrangler on Thu Oct 03 2024 21:17:24 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

export interface Bindings {
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	AUTH_SECRET: string;
	MAIL_USER: string;
	MAILGUN_API_KEY: string;
	MAILGUN_DOMAIN: string;
	DATABASE: D1Database;
}
