// Generated by Wrangler on Tue Sep 17 2024 22:55:35 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

export interface Bindings {
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	AUTH_SECRET: string;
	DATABASE: D1Database;
}
